### ISSUE TITLE
Users can create list items

### ISSUE THREAD

**Issue by skamansam** [BizziQuest/QuestListsFB#10]
Reference: Dashbord Tile, #22 
One of the actions on the List tile should be to add a list item. It should be one click to add, then the user should be able to start typing. Basically, there should be an empty item at the end of the list item preview which a user can just click on and start typing. In much the same way Google Keep works in its expanded view.

EDIT: The feel for this is to have each item in the list be editable. When you click on an item, it allows you to edit the text inline, instead of via a popup or other mechanism. At the end of the list, there will be an extra blank item that will allow you to add another item. As soon as a user begins typing in the blank item, a new blank item will appear below it. This should apply to the tile view and the full page view.

**Comment by KickButtowski80** [comment]
what do you mean by a user should associate with a list? like showing initial or picture? just FYI, we do not have any field that contains the first and last name of any user in Firestone.

**Comment by skamansam** [comment]
The description was upadted with more detail.

**Comment by KickButtowski80** [comment]
this adding action should be in page view of the list or the list tiles section?

**Comment by KickButtowski80** [comment]
so the master branch does not have dashboard tiles. I was wondering to know when you will merge it?  If I want to work on the list in a new branch and make it from the master branch, I cannot?

**Comment by skamansam** [comment]
> so the master branch does not have dashboard tiles. I was wondering to know when you will merge it? If I want to work on the list in a new branch and make it from the master branch, I cannot?

This comment is not relevant to this ticket. If you need a branch to be merged, add a comment on the related PR. If a PR or another feature is blocking something, take another ticket that is not being blocked.



> this adding action should be in page view of the list or the list tiles section?

It should be in both.

**Comment by KickButtowski80** [comment]
I added a pr for the user be able to view the full page list, and it is ready to be checked by you.
