### ISSUE TITLE
some of the files changes belong to another branch

### ISSUE THREAD

**Issue by KickButtowski80** [BizziQuest/QuestListsFB#12]
hope all is well with you

```
Unmerged paths:
  (use "git reset HEAD <file>..." to unstage)
  (use "git add <file>..." to mark resolution)

        both modified:   src/App.vue
        both modified:   src/components/LogInorSignUp.vue

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   src/components/DrawerMenu.vue
        modified:   src/components/TopMenuBar.vue

no changes added to commit (use "git add" and/or "git commit -a")
```

this is the output I get after git status and I feel all these changes must be added and committed into making-user-authentication-buttons
I tried to stash in create-list-for-authroized-users and stash pop them in making-user-authentication-buttons there and git commit and git add it, but create-list-for-authroized-users branch is more updated than the other one. 

First, I lost the code, but after a few seconds of remembering, it works now, I feel?

I am confused about what to do?

should I commit and add all changes inside create-list-for-authroized-users branch or 
you want it to be committed inside making-user-authentication-buttons because it is more appropriate to that branch?

**Comment by skamansam** [comment]
This doesn't say anything about what the actual changes are. You can cherry pick the changes you want, using interactive mode. See https://git-scm.com/book/en/v2/Git-Tools-Interactive-Staging for more on this.
