### ISSUE TITLE
Users should be able to edit their profile

### ISSUE THREAD

**Issue by skamansam** [BizziQuest/QuestListsFB#15]
```
As a logged in user,
When I click on my avatar in the top right,
I should be able to click on a menu item which
should allow me to edit information about myself
```
Also, as part of this ticket, the log out  button should be moved to a log out entry in the user menu.
Basically, when the user is logged in, they should see their avatar in the top right of the top bar, replacing the log in / sign up button. The avatar should open a menu which will give them options to update their profile or log out.

For now, a user's profile should contain an avatar upload/change and full name fields (first and last).  Make sure you display their email, but ensure it cannot be changed. The gist of the avatar is that if a user gets a random avatar they don't agree with, they should be able to change it. If you want to use a random avatar generator, make sure it can be randomized further or customized in some way.

**Comment by KickButtowski80** [comment]
I cannot find a ticket that asks to add a full name and photo URL upon sign up? I remember a ticket regarding to it was made?

**Comment by skamansam** [comment]
There isn't a ticket for the implementation of the avatar. For now, you can implement that feature any way you want.

**Comment by skamansam** [comment]
I updated the ticket with regards to what the profile should contain

**Comment by KickButtowski80** [comment]
note to myself, grab all the logic from store and put it inside a js file and export and import it later. devmeetup project sample
