### ISSUE TITLE
default state items colors are not always presented correctly

### ISSUE THREAD

**Issue by KickButtowski80** [BizziQuest/QuestListsFB#181]
Default state items are done and not done and should have been green and blue, yet they are blank 

![default-state-colors](https://user-images.githubusercontent.com/18540566/204164445-75e79574-f4ab-4ab1-bcf4-5316479a3e88.png)

**Comment by KickButtowski80** [comment]
I thought it is a bug, yet from what I was able to find, the colors are set to white color from the vue store.
It is possible that vue 3 is not being updated properly? 
please confirm that, so I can change the color

**Comment by skamansam** [comment]
You should include a way or method to reproduce this bug. If it is intermittent, please try to describe the conditions where it is not as it should be.

**Comment by skamansam** [comment]
This appears to only happen when the new questlist page is refreshed usign the browser. It does create the list with the colors, just not show them in the states editor.

**Comment by skamansam** [comment]
It uses the default store values instead of using the values from the defaultStates.
