### ISSUE TITLE
Init with Firebase and Flux store

### ISSUE THREAD

**Issue by skamansam** [BizziQuest/QuestListsFB#2]
This project needs a firebase backend, to begin with, but must support other backends as well. We need to create a Flux model with support for Firebase, to support long-term storage. There should be node tasks to handle common maintenance and development tasks, such as `firebase:deploy` or `firebase:serve`. The tasks *must* be prefixed with `firebase`.

**Comment by KickButtowski80** [comment]
I am using Firebase in past few month, and I never heard of Flux store or encounter it? Do I need to learn flux store cuz seemingly it is a thing lol ?
