### ISSUE TITLE
Users should be able to specify whether to use their Gravatar

### ISSUE THREAD

**Issue by skamansam** [BizziQuest/QuestListsFB#20]
We should allow users to be able to use their Gravatar as their avatar. Add a checkbox to the user profile edit form.

**Comment by KickButtowski80** [comment]
I have already done it, and it is ready to be checked.
It is located inside EditInfo.vue component.

**Comment by skamansam** [comment]
This is specific to Gravatar. This should be just a checkbox, then use the gravatar for the avatar. No need to input an address or anything.
