### ISSUE TITLE
Dashboard Tile(s)

### ISSUE THREAD

**Issue by skamansam** [BizziQuest/QuestListsFB#22]
The dashboard Tiles should be cards which contain an image, a title, a bar of action icons, and a few list items. For larger sizes, the image is on top, like a banner, with outlined title (text-shadow) on top of the image. (The reason for the outline is that outlined text is readable on any background color.)

Some cards will be larger than others, so there are two styles that are needed. These styles should be responsive.

Here is a  rough layout for the smaller size. 
```
_____________________________________________
|                |          [ Title ]       |
|                |        [description]     |
|                |  [description, cont'd]   |
| [ Image]       |  [ ] List Item 1         |
|                |  [ ] List Item 2         | 
|                |  [ ] List Item 3         |
|                |  [ ] List Item 4         |
|________________|__[edit icon]_[view icon]_|
```

Wider tile. For now, we aren't going to worry about the larger/wider sizes. We can get to that when we have more information on how to determine the larger sizes.
```
______________________________________________
|          [ Title with image background ]         |
|________ ____________________________________|
| [description ]                              |
|  [ ] List Item 1        |  [ ] List Item 3  |
|  [ ] List Item 2        |  [ ] List Item 4  |
|__________[edit icon]___[view icon]__________|
```

**Comment by KickButtowski80** [comment]
I have done some changes. They will be waited for being checked.
