### ISSUE TITLE
Users must be able to log in

### ISSUE THREAD

**Issue by skamansam** [BizziQuest/QuestListsFB#3]
Most data will be publicly accessible in Questlists, and state will be stored on the client. However, if we want users to be able to create lists, we need to hold them accountable, so we need to be able to create lists and assign them a creator. In order to do this, we need to allow users to sign up. We should probably allow all OAuth methods, as well as simple username/password login. We need to have a login modal or popup as well as a global method for setting long-term user data. 

Deliverables:
* Login window or popup. Must not ne a new page.
* Sign in, sign up, and logout methods in the Flux store
* Global sign in and sign out links which show the login window/popup. Must not redirect on signin.

**Comment by KickButtowski80** [comment]
again flux store? firebase has authentication part which does not need any flux store? are you talking about React or Vue? I am confused :/
