### ISSUE TITLE
Users should be able to set more preferences for ListItem states.

### ISSUE THREAD

**Issue by skamansam** [BizziQuest/QuestListsFB#35]
Note: this is a redesign of the states UX in the list preferences dialog. 

The new UX should have only a list of items in it and should be in the same preferences dialog. The existing add button and the entry field should be removed and only a list should be there. It should function the same as the List page, where there will always be an empty item at the bottom of the list where users can create new items. 

This is what the UX should look like:
![image](https://user-images.githubusercontent.com/102971/87507481-77975d00-c63b-11ea-8e87-9701d65f0ed2.png)

Here is a gif of, roughly, what the dialogs should look like:
![listItemStateUX](https://user-images.githubusercontent.com/102971/87508948-79aeeb00-c63e-11ea-8d1e-88de45fc6bc3.gif)

Sorting:
The list of states should be an ordered, sortable list of items which defaults to the Done/Not Done options. There should be handles on the left of each item which can be used to drag the items so they can be sorted.

The next item in the row should be the icon for the state. When clicked, a simple, compact dialog should be displayed, with links for how to find the icon string. There should be a row where the icon is displayed on the left, with the rest of the row filled with a text entry. When the dialog is opened, the text field should have focus. When a user types in the text field, the icon should be automatically updated. When the user presses enter, the dialog should close and the text should be used as the icon string for that state. There should be no close button or any other way to close the dialog, except clicking outside the dialog.

The next item in the row should be the color of this state. It should be the same palette chooser as the other color selector. (It should use the same component.) This should default to nothing. It will be used to change the color of the rows when the item is in that state. (In another ticket.)
The next item in the row should be the text. This is a user-friendly version that will be used where the icon can't be shown, and as alt text. The key in the states object in datastore should be this string, for easy lookups. Using the same string should not be allowed.

The final item in the row should be the value of that option, and can be anything, but the index number should be the default.
At the end, there should be a blank entry that should be auto-filled when one of the items is changed. Basically, this should reflect the UX of the list view.

We should plan on using the data structure as outlined in #33

**Comment by skamansam** [comment]
Here is the createAlist file I used to create the above gifs:

```
<template>
  <v-row justify="center">
    <v-dialog v-model="showSelectIcon" persistent max-width="600px" class="primary">
    <v-card>
        <v-card-title class="headline">Which icon would you like to use?</v-card-title>
        <v-card-text>
          <v-text-field :prepend-icon="selectIcon" :value="selectIcon"></v-text-field>
        </v-card-text>
        <v-card-actions>
          <v-spacer></v-spacer>
          <v-btn
            color="green darken-1"
            text
            @click="showSelectIcon = false"
          >
            Cancel
          </v-btn>
          <v-btn
            color="green darken-1"
            text
            @click="showSelectIcon = false"
          >
            Select
          </v-btn>
        </v-card-actions>
      </v-card>    </v-dialog>
    <v-dialog v-model="dialog" persistent max-width="600px" class="primary">
      <template v-slot:activator="{ on }">
        <v-list-item link v-on="on">
          <v-list-item-action>
            <v-icon color="secondary">add</v-icon>
          </v-list-item-action>
          <v-list-item-content>
            <v-list-item-title color="secondary">create a list</v-list-item-title>
          </v-list-item-content>
        </v-list-item>
      </template>
      <v-card>
        <v-card-title>
          <span class="headline">Create A List</span>
        </v-card-title>
        <v-card-text>
        <v-container>
          <v-form ref="form" @submit.prevent="">
            <v-row>
              <v-col cols="12" sm="6" md="6">
                <v-text-field
                label="Title*"
                :rules = "titleRules"
                 v-model='title'
                 required
                 placeholder="Your Title"
                 outlined></v-text-field>
              </v-col>
              <v-col cols="12" sm="6" md="6">
                <v-text-field
                label="Color*"
                :rules = "colorPickerRules"
                 v-model="color"
                 placeholder="#FFFFFF"
                 outlined>
                  <template v-slot:append>
                    <v-menu>
                      <template v-slot:activator="{ on }">
                        <div :style="swatchStyle()" v-on="on" />
                      </template>
                      <v-card>
                        <v-card-text>
                          <v-color-picker v-model="color" flat />
                        </v-card-text>
                      </v-card>
                    </v-menu>
                  </template>
                </v-text-field>
              </v-col>
            </v-row>
            </v-form>
            <v-row>
              <h3>Possible Item States:</h3>
            </v-row>
            <v-row>
              <ul style="list-style-type: none;">
                <li v-for="item in states" :key="item.title">
                  <v-icon>mdi-drag</v-icon>
                  <v-icon @click="doSelectIcon(item.icon)">{{item.icon}}</v-icon>
                  <v-text-field dense :value="item.title" style="display: inline-block;"></v-text-field>
                </li>
                <li>
                  <v-icon>mdi-drag</v-icon>
                  <v-icon>mdi-plus</v-icon>
                  <v-text-field dense placeholder="New Item State" style="display: inline-block;"></v-text-field>
                </li>
              </ul>
              <!-- <v-col cols="12" sm="6" md="6">
                <v-form ref="addStateForm">
                  <v-text-field
                  label="New State*"
                  :rules = "newStateRules"
                  :lazy-validation="true"
                  v-model="newState"
                  placeholder="Your Condition"
                  outlined>
                  </v-text-field>
                  <v-btn v-on:click="addState" class="primary">Add</v-btn>
                  </v-form>
                </v-col>
              <v-col cols="12" sm="6" md="6">
                <span>Availabe States</span>
                <div id="availableListStates">
                  <ul>
                    <li v-for="item in states" :key="item.state">{{ item }}</li>
                  </ul>
                </div>
              </v-col>
            -->
            </v-row>

          </v-container>
          <small>*indicates required field</small>
        </v-card-text>
        <v-card-actions>
          <v-spacer></v-spacer>
          <v-btn color="blue darken-1" text @click="resetTheForms">Close</v-btn>
          <v-btn color="blue darken-1" text @click="createAList">Create</v-btn>
        </v-card-actions>
      </v-card>
     </v-dialog>
  </v-row>
</template>

<script>
export default {
  name: 'CreateAList',
  data() {
    return {
      color: '#A0E9C9FF',
      title: '',
      menu: false,
      dialog: false,
      showSelectIcon: false,
      selectIcon: false,
      newState: '',
      states: [
        {
          title: 'Not Done',
          icon: 'mdi-checkbox-blank-outline',
        },
        {
          title: 'Done',
          icon: 'mdi-checkbox-marked-outline',
        },
        {
          title: 'Face!',
          icon: 'mdi-face',
        },
      ],
      newItem: '',
      statesPicked: '',
      titleRules: [
        (v) => !!v || 'Title is required',
        (v) => (v && v.length > 5) || 'Title must be longer than 5 characters',
      ],
      colorPickerRules: [
        (v) => !!v || 'Color is required',
        (v) => /^#[0-9A-F]{8}$/i.test(v) || 'Color Format Must be #FFFFFF',
      ],
      newStateRules: [
        (v) => !!v || 'State is required',
        (v) => (v && v.length >= 5) || 'State must be at least 5 characters',
      ],
    };
  },
  methods: {
    doSelectIcon(icon) {
      this.showSelectIcon = true;
      this.selectIcon = icon;
    },
    addState() {
      if (this.$refs.addStateForm.validate()) {
        this.states.push(this.newState);
        this.$refs.addStateForm.reset();
      }
    },
    createAList() {
      this.$refs.addStateForm.validate();
      if (this.$refs.form.validate()) {
        const payload = {};
        payload.title = this.title;
        payload.bgColor = this.color;
        payload.states = this.states;
        this.$store.dispatch('createAList', payload);
        this.$refs.form.reset();
        this.$refs.addStateForm.reset();
        this.dialog = false;
      }
    },
    resetTheForms() {
      this.dialog = false;
      this.$refs.form.reset();
      this.$refs.addStateForm.reset();
      this.color = '#A0E9C9FF';
    },
    swatchStyle() {
      return {
        backgroundColor: this.color,
        cursor: 'pointer',
        height: '30px',
        width: '30px',
        borderRadius: '4px',
        transition: 'border-radius 200ms ease-in-out',
      };
    },
  },
  computed: {
    itemStates() {
      return this.$store.getters.itemStates;
    },
  },
};
</script>

<style   scoped>
#availableListStates{
   height: 100px;
   overflow: auto;
}

</style>

```

**Comment by KickButtowski80** [comment]
I have a huge dilemma about an index which is changed during startDrag and endDrag .
from my investigation, I just found out that the index is changed for example, from 0 to 3 based on target location? behind the scene, it knows when it is in item index zero and when it is going to end up in the third time for example.
I was able to find data-index from evet.currentTraget.dataset, so passing the index to startDrag will be useless? because event.currentTarget is the event that startDrag is attached to, yet event.target is the element that triggers the event. it seems the info that currentTraget has vs traget is different. 
again, I want to have more readable index because using index for drag and drop is confusing. 
last point, how the drop zone which is outer div is going to understand the right index?

Again, it seems all this happens behind the scene because it is the only way that makes sense to me.

could you please share your thoughts and tell me what you think about what I have jotted down?

**Comment by skamansam** [comment]
Drag n drop is just an interface - user experience - for sorting the list. We aren't sorting in-place, we are using this mechanism to find an order, then we are reordering the list. We use the data-index attribute as a means to find the element onto  which we are dropping. We can use a class instead, if you want. We went with the data-index attribute because you said you wanted to use event.target instead of passing the index. An alternative to what we have, and one that may be clearer, is to pass the index to the onDrop handler, and use a class as a selector.

**Comment by KickButtowski80** [comment]
based on my investigation, even when index argument was switched to data-index, it acts the same as when the index was used. What do I mean?
I meant that during the drag and drop value of data-index will be changed based on the location that starts the dragging and ends the dragging. 
Something behind the curtain?
