### ISSUE TITLE
Logged in users must be able to create a list

### ISSUE THREAD

**Issue by skamansam** [BizziQuest/QuestListsFB#4]
```gherkin
As a logged in user,
I must be able to create a list,
In order to store lists. 
```
```gherkin
As an anonymous user,
I cannot create a list.
```
```
As a logged in user,
When I create a list,
I must be able to specify a title for that list.
```

```
As a logged in user,
When I create a list,
I must be able to specify a color for that list.
```
```
As a logged in user,
When I create a list,
I must be able to create a list of states for that list,
Where the default states are ['not done', 'done'],
so that I can set those states on individual items. 
```
```
As a logged in user,
When I create a list,
I must be able to specify a cover image for that list,
which I can upload,
in order to set the cover image for the collapsed tile.
```

**Comment by KickButtowski80** [comment]
what kind of list are we talking about?

**Comment by skamansam** [comment]
NOTE: The default dashboard view will be a tiled view of the most recently used and popular lists. Each tile will be similar to the tiles at https://vuetifyjs.com/en/components/cards/#grids. So the cover image is the image which is shown on the tile, not really an "avatar," as was mentioned in our call. However, it doesn't really matter for now - we can work on how we are going to use this data later.

**Comment by KickButtowski80** [comment]
I am sorry to close and reopen this ticket 
Could you please clarify the following? 
"As a logged-in user,
When I create a list,
I must be able to specify a cover image for that list,
which I can upload,
in order to set the cover image for the collapsed tile."

**Comment by skamansam** [comment]
In the dashboard view, the lists will be nothing more than tiles. The background of the tiles should have a photo, much like an album cover for a CD or record.

**Comment by skamansam** [comment]
For more on the Tiles, see #22
