### ISSUE TITLE
Add Site Search

### ISSUE THREAD

**Issue by skamansam** [BizziQuest/QuestListsFB#48]
~~Since we can't do full text search in firebase, an easy solution to start with is the google programmable search. Here is a  URL explaining how to implement it:~~
~~https://support.google.com/programmable-search/answer/4513751?hl=en&ref_topic=4513742&visit_id=637312500270360151-3890492741&rd=1~~

Since google forces ads for site search, we are going to go with the recommended site search: Algolia.

**Comment by KickButtowski80** [comment]
it was not mentioned where to reside the google programmable search, so for now, I will put it in card lists.
